"""empty message

Revision ID: 351539d84da3
Revises: 
Create Date: 2024-03-01 11:19:51.861980

"""

import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision = "351539d84da3"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("login", sa.String(length=80), nullable=False),
        sa.Column("email", sa.String(length=120), nullable=False),
        sa.Column("password", sa.String(length=256), nullable=False),
        sa.Column("country_code", sa.String(length=2), nullable=False),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("phone", sqlalchemy_utils.types.phone_number.PhoneNumberType(length=20), nullable=True),
        sa.Column("image", sa.String(length=256), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("login"),
    )
