import os

from dotenv import find_dotenv, load_dotenv

load_dotenv()
e = os.getenv

SERVER_PORT = e("SERVER_PORT")
SERVER_ADDRESS = e("SERVER_ADDRESS")
POSTGRES_CONN = e("POSTGRES_CONN")
POSTGRES_USERNAME = e("POSTGRES_USERNAME")
POSTGRES_PASSWORD = e("POSTGRES_PASSWORD")
POSTGRES_PORT = e("POSTGRES_PORT")
POSTGRES_HOST = e("POSTGRES_HOST")
POSTGRES_DATABASE = e("POSTGRES_DATABASE")
JWT_SECRET_KEY = e("JWT_SECRET_KEY")


DEBUG = e("DEBUG", default=True)
